INSERT INTO SP_MPA (ID, NAME)
VALUES (1, 'G'),(2, 'PG'),(3, 'PG_13'),(4, 'R'),(5, 'NC_17');

INSERT INTO SP_GENRE (ID, NAME)
VALUES (1, 'COMEDY'),(2, 'DRAMA'),(3, 'CARTOON'),(4, 'THRILLER'),(5, 'DOCUMENTARY'),(6, 'ACTION_MOVIE');

INSERT INTO SP_FRIENDSHIP_STATUS (ID, NAME)
VALUES (1, 'PENDING'),(2, 'ACCEPTED');